In [ ]:
import pandas as pd

# Basics

In [ ]:
df = pd.read_csv('/content/sample_data/weather.csv')

In [ ]:
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [ ]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [ ]:
df.Temperature

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [ ]:
df['Temperature'].max()

50

In [ ]:
df['EST'][df['Events']=='Rain']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

In [ ]:
df['WindSpeedMPH'].mean()

np.float64(6.892857142857143)

In [ ]:
df.isnull().sum()

EST                      0
Temperature              0
DewPoint                 0
Humidity                 0
Sea Level PressureIn     0
VisibilityMiles          0
WindSpeedMPH             3
PrecipitationIn          0
CloudCover               0
Events                  22
WindDirDegrees           0
dtype: int64

In [ ]:
df.fillna(0, inplace=True)
df.isnull().sum()

EST                     0
Temperature             0
DewPoint                0
Humidity                0
Sea Level PressureIn    0
VisibilityMiles         0
WindSpeedMPH            0
PrecipitationIn         0
CloudCover              0
Events                  0
WindDirDegrees          0
dtype: int64

In [ ]:
import pandas as pd
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(weather_data)
# df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.to_csv('/content/sample_data/weather_data.csv')

In [ ]:
df.shape

(6, 3)

In [ ]:
df.tail() # df.tail(2)

            day  temperature  windspeed
event
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [ ]:
df[1:3]

            day  temperature  windspeed
event
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2

In [ ]:
df.columns

Index(['day', 'temperature', 'windspeed'], dtype='object')

In [ ]:
df['day'] # or df.day

event
Rain     1/1/2017
Sunny    1/2/2017
Snow     1/3/2017
Snow     1/4/2017
Rain     1/5/2017
Sunny    1/6/2017
Name: day, dtype: object

In [ ]:
type(df['day'])

pandas.core.series.Series

In [ ]:
df[['day','temperature']]

            day  temperature
event
Rain   1/1/2017           32
Sunny  1/2/2017           35
Snow   1/3/2017           28
Snow   1/4/2017           24
Rain   1/5/2017           32
Sunny  1/6/2017           31

In [ ]:
df[df['temperature']>32]

            day  temperature  windspeed
event
Sunny  1/2/2017           35          7

In [ ]:
df['day'][df['temperature'] == df['temperature'].max()] # Kinda doing SQL in pandas

event
Sunny    1/2/2017
Name: day, dtype: object

In [ ]:

df[df['temperature'] == df['temperature'].max()] # Kinda doing SQL in pandas

            day  temperature  windspeed
event
Sunny  1/2/2017           35          7

In [ ]:
df['temperature'].std()

3.8297084310253524

In [ ]:
df['event'].max() # But max() won't work since data type is string

KeyError: 'event'

In [ ]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [ ]:
df.set_index('day')

          temperature  windspeed
day
1/1/2017           32          6
1/2/2017           35          7
1/3/2017           28          2
1/4/2017           24          7
1/5/2017           32          4
1/6/2017           31          2

In [ ]:
df

        day  temperature  windspeed
0  1/1/2017           32          6
1  1/2/2017           35          7
2  1/3/2017           28          2
3  1/4/2017           24          7
4  1/5/2017           32          4
5  1/6/2017           31          2

In [ ]:
df.set_index('day', inplace=True)
df

          temperature  windspeed
day
1/1/2017           32          6
1/2/2017           35          7
1/3/2017           28          2
1/4/2017           24          7
1/5/2017           32          4
1/6/2017           31          2

In [ ]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='object', name='day')

In [ ]:
df.loc['1/2/2017']

temperature    35
windspeed       7
Name: 1/2/2017, dtype: int64

In [ ]:
df.reset_index(inplace=True)
df.head()

        day  temperature  windspeed
0  1/1/2017           32          6
1  1/2/2017           35          7
2  1/3/2017           28          2
3  1/4/2017           24          7
4  1/5/2017           32          4

In [ ]:
df = pd.DataFrame(weather_data)
df.set_index('event',inplace=True) # this is kind of building a hash map using event as a key
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7

# Ways of creating dataframes

In [ ]:
# using csv

df = pd.read_csv("/content/sample_data/weather_data.csv")
df

   event       day  temperature  windspeed
0   Rain  1/1/2017           32          6
1  Sunny  1/2/2017           35          7
2   Snow  1/3/2017           28          2
3   Snow  1/4/2017           24          7
4   Rain  1/5/2017           32          4
5  Sunny  1/6/2017           31          2

In [ ]:
# using excel

df=pd.read_excel("/content/sample_data/weather_data.xlsx","Sheet1")
df

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [ ]:
# Using dictionary

import pandas as pd
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'windspeed': [6,7,2],
    'event': ['Rain', 'Sunny', 'Snow']
}
df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [ ]:
# Using tuples

weather_data = [
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'])
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [ ]:
# Using list of dictionaries

weather_data = [
    {'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},
    {'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},
    {'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},

]
df = pd.DataFrame(data=weather_data, columns=['day','temperature','windspeed','event'])
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

# Read and Write Dataframes

In [ ]:
import pandas as pd

df = pd.read_csv("/content/sample_data/stock_data.csv")
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
df = pd.read_csv("/content/sample_data/stock_data.csv", skiprows=1)
df

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [ ]:
df = pd.read_csv("/content/sample_data/stock_data.csv", header=1) # skiprows and header are kind of same
df

  GOOGL          27.82   87   845     larry page
0   WMT           4.61  484    65           n.a.
1  MSFT             -1   85    64     bill gates
2  RIL   not available   50  1023  mukesh ambani
3  TATA            5.6   -1  n.a.     ratan tata

In [ ]:
df = pd.read_csv("/content/sample_data/stock_data.csv", header=None, names = ["ticker","eps","revenue","people"])
df

                ticker      eps revenue         people
tickers            eps  revenue   price         people
GOOGL            27.82       87     845     larry page
WMT               4.61      484      65           n.a.
MSFT                -1       85      64     bill gates
RIL      not available       50    1023  mukesh ambani
TATA               5.6       -1    n.a.     ratan tata

In [ ]:
df = pd.read_csv("/content/sample_data/stock_data.csv",  nrows=2)
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.

In [ ]:
df = pd.read_csv("/content/sample_data/stock_data.csv", na_values=["n.a.", "not available"])
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82       87   845.0     larry page
1     WMT   4.61      484    65.0            NaN
2    MSFT  -1.00       85    64.0     bill gates
3    RIL     NaN       50  1023.0  mukesh ambani
4    TATA   5.60       -1     NaN     ratan tata

In [ ]:
df = pd.read_csv("/content/sample_data/stock_data.csv",  na_values={
        'eps': ['not available'],
        'revenue': [-1],
        'people': ['not available','n.a.']
    })
df

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65            NaN
2    MSFT  -1.00     85.0    64     bill gates
3    RIL     NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [ ]:
df.to_csv("new.csv", index=False)

In [ ]:
df.to_csv("new2.csv",header=False)

In [ ]:
df.to_csv("new3.csv", columns=["tickers","price"], index=False)

In [ ]:
df = pd.read_excel("/content/sample_data/stock_data.xlsx","Sheet1")
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
def convert_people_cell(cell):
    if cell=="n.a.":
        return 'Sam Walton'
    return cell

def convert_price_cell(cell):
    if cell=="n.a.":
        return 50
    return cell

df = pd.read_excel("/content/sample_data/stock_data.xlsx","Sheet1", converters= {
        'people': convert_people_cell,
        'price': convert_price_cell
    })
df

  tickers            eps  revenue  price         people
0   GOOGL          27.82       87    845     larry page
1     WMT           4.61      484     65     Sam Walton
2    MSFT             -1       85     64     bill gates
3    RIL   not available       50   1023  mukesh ambani
4    TATA            5.6       -1     50     ratan tata

In [ ]:
df.to_excel("new.xlsx", sheet_name="stocks", index=False, startrow=2, startcol=1)

In [ ]:
# Write two dataframes to two separate sheets in excel


df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64 ],
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

df_weather =  pd.DataFrame({
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']
})

In [ ]:
with pd.ExcelWriter('stocks_weather2.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name="stocks")
    df_weather.to_excel(writer, sheet_name="weather")