# **University of Asia Pacific**
**Department of Computer Science and Engineering**
**Course Code:** CSE 414
**Course Title:** Machine Learning and Deep Learning Lab
**Section:** B | **Fall - 25** | **Quiz - 01** |    
**Set - A**
**Date:** 03/03/26
**Total Marks:** 10 | **Duration:** 20 Minutes

---

## **Instructions:**
- Complete all tasks sequentially.
- Carefully observe array shapes after each operation.
- Submit a single Jupyter Notebook (.ipynb) file with the filename format: **Section_Set_StudentID**
- Clearly label each task in your submission.

---

## **Tasks:**
1. *Create a 1D array of 10 random integers between 1 and 50.*
2. *Reshape the above 10-element array into a 2x5 2D matrix.*
3. *Create a DataFrame from a dictionary containing names and marks of 3 students.*
4. *Use the `head()` function to display only the first 2 rows of your student DataFrame.*
5. *Rename one column of your DataFrame using the `rename()` method.*

6. *Create an array with values from 0 to 9 and extract all odd numbers.*
7. *Extract the first two rows and first two columns from a 4x4 NumPy array.*
8. *Given a DataFrame `df`, filter it to show only rows where a column 'Age' is greater than 25.*
9. *Select only the 'Name' and 'Salary' columns from an existing DataFrame.*
10. *Find and print the unique values in a specific column of your DataFrame.*

In [3]:

# Task 1: Create a 1D array of 10 random integers between 1 and 50
import numpy as np
arr = np.random.randint(1, 51, size=10)
arr

array([34, 43, 21, 25, 23, 35,  5, 18, 31, 48], dtype=int32)

In [5]:
# Task 2: Reshape the above 10-element array into a 2x5 2D matrix
arr_reshaped = arr.reshape(2, 5)
arr_reshaped

array([[34, 43, 21, 25, 23],
       [35,  5, 18, 31, 48]], dtype=int32)

In [14]:
# Task 3: Create a DataFrame from a dictionary containing names and marks of 3 students
import pandas as pd
data = {'Name': ['Sakhawat', 'Rakib', 'Shahin'], 'Marks': [85, 90, 88]}
df = pd.DataFrame(data)
df

       Name  Marks
0  Sakhawat     85
1     Rakib     90
2    Shahin     88

In [15]:
# Task 4: Use the `head()` function to display only the first 2 rows of your student DataFrame
df.head(2)

       Name  Marks
0  Sakhawat     85
1     Rakib     90

In [16]:
# Task 5: Rename one column of your DataFrame using the `rename()` method
df.rename(columns={'Marks': 'Score'}, inplace=True)
df

       Name  Score
0  Sakhawat     85
1     Rakib     90
2    Shahin     88

In [17]:
# Task 6: Create an array with values from 0 to 9 and extract all odd numbers
arr_odd = np.arange(10)[np.arange(10) % 2 != 0]
arr_odd

array([1, 3, 5, 7, 9])

In [18]:
# Task 7: Extract the first two rows and first two columns from a 4x4 NumPy array
arr_4x4 = np.arange(16).reshape(4, 4)
arr_4x4[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [19]:
# Task 8: Given a DataFrame `df`, filter it to show only rows where a column 'Age' is greater than 25
df_age = pd.DataFrame({'Name': ['Shohag', 'Mehedi', 'Hridoy'], 'Age': [24, 30, 28]})
df_age[df_age['Age'] > 25]

     Name  Age
1  Mehedi   30
2  Hridoy   28

In [20]:
# Task 9: Select only the 'Name' and 'Salary' columns from an existing DataFrame
df_salary = pd.DataFrame({'Name': ['Partho', 'Rakib', 'Sakhawat'], 'Salary': [50000, 55000, 60000]})
df_salary[['Name', 'Salary']]

       Name  Salary
0    Partho   50000
1     Rakib   55000
2  Sakhawat   60000

In [21]:
# Task 10: Find and print the unique values in a specific column of your DataFrame
df_unique = pd.DataFrame({'Name': ['Partho', 'Rakib', 'Sakhawat']})
df_unique['Name'].unique()

array(['Partho', 'Rakib', 'Sakhawat'], dtype=object)